apiVersion: v1
kind: Service
metadata:
  name: gni-api
  namespace: gni
  labels:
    app: gni-api
    app.kubernetes.io/name: gni
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: gni-api
