apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gni

resources:
  - ../../base

patches:
  - path: patch-resources.yaml

images:
  - name: ghcr.io/your_user/gni-api:latest
    newName: ghcr.io/your_user/gni-api
    newTag: v1.0.0
  - name: ghcr.io/your_user/gni-worker:latest
    newName: ghcr.io/your_user/gni-worker
    newTag: v1.0.0
